import type { DashboardData } from './types';

export const mockDashboardData: DashboardData = {
  revenue: {
    total: 284750,
    growth: 12.5,
    byPeriod: [
      // Weekly revenue for last 12 weeks
      { period: 'Week 1', revenue: 18500, packages: 42 },
      { period: 'Week 2', revenue: 21300, packages: 51 },
      { period: 'Week 3', revenue: 19800, packages: 45 },
      { period: 'Week 4', revenue: 23400, packages: 56 },
      { period: 'Week 5', revenue: 22100, packages: 48 },
      { period: 'Week 6', revenue: 25600, packages: 62 },
      { period: 'Week 7', revenue: 24300, packages: 58 },
      { period: 'Week 8', revenue: 26800, packages: 64 },
      { period: 'Week 9', revenue: 25400, packages: 60 },
      { period: 'Week 10', revenue: 28900, packages: 71 },
      { period: 'Week 11', revenue: 27200, packages: 65 },
      { period: 'Week 12', revenue: 31450, packages: 78 },
    ],
    byPackage: [
      {
        id: 'pkg-1',
        name: 'Basic Package',
        purchases: 324,
        revenue: 48600,
        successRate: 94.5,
      },
      {
        id: 'pkg-2',
        name: 'Standard Package',
        purchases: 256,
        revenue: 76800,
        successRate: 96.2,
      },
      {
        id: 'pkg-3',
        name: 'Premium Package',
        purchases: 189,
        revenue: 94500,
        successRate: 97.8,
      },
      {
        id: 'pkg-4',
        name: 'Enterprise Package',
        purchases: 87,
        revenue: 130500,
        successRate: 98.9,
      },
      {
        id: 'pkg-5',
        name: 'Student Package',
        purchases: 412,
        revenue: 41200,
        successRate: 92.1,
      },
    ],
    topSpenders: [
      {
        id: 'user-1',
        name: 'John Anderson',
        email: 'john.anderson@company.com',
        totalSpent: 4850,
        purchases: 8,
      },
      {
        id: 'user-2',
        name: 'Sarah Mitchell',
        email: 'sarah.mitchell@enterprise.com',
        totalSpent: 4200,
        purchases: 6,
      },
      {
        id: 'user-3',
        name: 'Michael Chen',
        email: 'michael.chen@tech.com',
        totalSpent: 3950,
        purchases: 7,
      },
      {
        id: 'user-4',
        name: 'Emily Rodriguez',
        email: 'emily.r@startup.io',
        totalSpent: 3680,
        purchases: 5,
      },
      {
        id: 'user-5',
        name: 'David Kim',
        email: 'david.kim@business.com',
        totalSpent: 3420,
        purchases: 6,
      },
      {
        id: 'user-6',
        name: 'Lisa Thompson',
        email: 'lisa.t@corp.com',
        totalSpent: 3100,
        purchases: 5,
      },
      {
        id: 'user-7',
        name: 'James Wilson',
        email: 'james.wilson@firm.com',
        totalSpent: 2890,
        purchases: 4,
      },
      {
        id: 'user-8',
        name: 'Maria Garcia',
        email: 'maria.garcia@company.net',
        totalSpent: 2750,
        purchases: 5,
      },
      {
        id: 'user-9',
        name: 'Robert Taylor',
        email: 'robert.t@enterprise.org',
        totalSpent: 2580,
        purchases: 4,
      },
      {
        id: 'user-10',
        name: 'Jennifer Lee',
        email: 'jennifer.lee@business.io',
        totalSpent: 2450,
        purchases: 4,
      },
    ],
    transactions: {
      total: 1268,
      success: 1215,
      failed: 53,
      successRate: 95.8,
      failureRate: 4.2,
    },
  },
  users: {
    total: 8542,
    new: 342,
    active: 6784,
    growth: 8.3,
  },
  feedback: {
    total: 2847,
    averageRating: 4.3,
    distribution: [
      { rating: 5, count: 1523, percentage: 53.5 },
      { rating: 4, count: 824, percentage: 28.9 },
      { rating: 3, count: 312, percentage: 11.0 },
      { rating: 2, count: 125, percentage: 4.4 },
      { rating: 1, count: 63, percentage: 2.2 },
    ],
    sentimentBreakdown: {
      good: 2347, // 5 & 4 stars
      medium: 312, // 3 stars
      bad: 188, // 1 & 2 stars
    },
  },
  reports: {
    total: 456,
    byType: [
      { type: 'Technical Issue', count: 142, percentage: 31.1 },
      { type: 'Content Error', count: 98, percentage: 21.5 },
      { type: 'Payment Problem', count: 76, percentage: 16.7 },
      { type: 'Account Access', count: 65, percentage: 14.3 },
      { type: 'UI/UX Bug', count: 43, percentage: 9.4 },
      { type: 'Performance', count: 32, percentage: 7.0 },
    ],
  },
  games: {
    totalPlays: 45678,
    gameStats: [
      {
        id: 'game-1',
        name: 'TRIZ Pattern Master',
        plays: 12543,
        averageScore: 7850,
        completionRate: 78.5,
      },
      {
        id: 'game-2',
        name: 'Innovation Challenge',
        plays: 10234,
        averageScore: 6920,
        completionRate: 72.3,
      },
      {
        id: 'game-3',
        name: 'Problem Solver Quest',
        plays: 8967,
        averageScore: 8420,
        completionRate: 81.2,
      },
      {
        id: 'game-4',
        name: 'Creative Thinking Arena',
        plays: 7845,
        averageScore: 7240,
        completionRate: 68.9,
      },
      {
        id: 'game-5',
        name: 'Principle Explorer',
        plays: 6089,
        averageScore: 6580,
        completionRate: 65.4,
      },
    ],
    topPlayers: [
      {
        id: 'player-1',
        name: 'Alex Champion',
        avatar: '👑',
        score: 125400,
        gamesPlayed: 247,
      },
      {
        id: 'player-2',
        name: 'Jordan Pro',
        avatar: '🏆',
        score: 118900,
        gamesPlayed: 223,
      },
      {
        id: 'player-3',
        name: 'Taylor Ace',
        avatar: '⭐',
        score: 112300,
        gamesPlayed: 215,
      },
      {
        id: 'player-4',
        name: 'Morgan Elite',
        avatar: '🎯',
        score: 107800,
        gamesPlayed: 198,
      },
      {
        id: 'player-5',
        name: 'Casey Master',
        avatar: '💎',
        score: 101200,
        gamesPlayed: 189,
      },
      {
        id: 'player-6',
        name: 'Riley Expert',
        avatar: '🚀',
        score: 98600,
        gamesPlayed: 176,
      },
      {
        id: 'player-7',
        name: 'Sam Winner',
        avatar: '🌟',
        score: 94300,
        gamesPlayed: 168,
      },
      {
        id: 'player-8',
        name: 'Jamie Legend',
        avatar: '⚡',
        score: 89700,
        gamesPlayed: 154,
      },
    ],
    mostPlayed: {
      id: 'game-1',
      name: 'TRIZ Pattern Master',
      plays: 12543,
      averageScore: 7850,
      completionRate: 78.5,
    },
  },
  chat: {
    totalMessages: 34567,
    botMessages: 17890,
    userMessages: 16677,
    averageResponseTime: 2.3, // seconds
    satisfactionRating: 4.2,
    satisfactionBreakdown: {
      satisfied: 2845,
      neutral: 678,
      unsatisfied: 234,
    },
  },
  forum: {
    totalPosts: 1876,
    totalComments: 8943,
    totalVotes: 15678,
    activeUsers: 1247,
    topPosts: [
      {
        id: 'post-1',
        title: 'Advanced TRIZ Techniques for Product Innovation',
        author: 'Dr. Innovation',
        votes: 342,
        comments: 87,
        createdAt: '2025-11-20',
      },
      {
        id: 'post-2',
        title: 'How I Used TRIZ to Solve a Critical Business Problem',
        author: 'Tech_Solver',
        votes: 298,
        comments: 64,
        createdAt: '2025-11-18',
      },
      {
        id: 'post-3',
        title: 'Complete Guide to Contradiction Matrix',
        author: 'TRIZ_Master',
        votes: 276,
        comments: 53,
        createdAt: '2025-11-15',
      },
      {
        id: 'post-4',
        title: 'Real-World TRIZ Applications in Software Development',
        author: 'DevThinkTank',
        votes: 254,
        comments: 72,
        createdAt: '2025-11-22',
      },
      {
        id: 'post-5',
        title: 'TRIZ vs Design Thinking: A Comprehensive Comparison',
        author: 'InnoStrategy',
        votes: 231,
        comments: 58,
        createdAt: '2025-11-12',
      },
      {
        id: 'post-6',
        title: 'Beginner-Friendly TRIZ Principles Explained',
        author: 'LearnTRIZ',
        votes: 218,
        comments: 91,
        createdAt: '2025-11-25',
      },
      {
        id: 'post-7',
        title: 'Case Study: Using TRIZ in Manufacturing Optimization',
        author: 'Industry_Expert',
        votes: 203,
        comments: 45,
        createdAt: '2025-11-10',
      },
      {
        id: 'post-8',
        title: 'Common Mistakes When Learning TRIZ',
        author: 'MentorPro',
        votes: 189,
        comments: 67,
        createdAt: '2025-11-08',
      },
    ],
  },
};
