/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as MatrixTrizRouteImport } from './routes/matrix-triz'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LearnTrizRouteImport } from './routes/learn-triz'
import { Route as HomeRouteImport } from './routes/home'
import { Route as FlashcardDeckRouteImport } from './routes/flashcard-deck'
import { Route as R6StepsRouteRouteImport } from './routes/6-steps/route'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegisterIndexRouteImport } from './routes/register.index'
import { Route as PackagesIndexRouteImport } from './routes/packages.index'
import { Route as ForgotPasswordIndexRouteImport } from './routes/forgot-password.index'
import { Route as CourseIndexRouteImport } from './routes/course.index'
import { Route as BooksIndexRouteImport } from './routes/books.index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as RegisterVerifyOtpRouteImport } from './routes/register.verify-otp'
import { Route as ForgotPasswordVerifyOtpRouteImport } from './routes/forgot-password.verify-otp'
import { Route as ForgotPasswordNewPasswordRouteImport } from './routes/forgot-password.new-password'
import { Route as FlashcardDeckIdRouteImport } from './routes/flashcard.$deckId'
import { Route as CourseSlugRouteImport } from './routes/course.$slug'
import { Route as AdminTransactionsRouteRouteImport } from './routes/admin/transactions/route'
import { Route as AdminSubscriptionsRouteRouteImport } from './routes/admin/subscriptions/route'
import { Route as AdminQuizzesRouteRouteImport } from './routes/admin/quizzes/route'
import { Route as AdminPackagesRouteRouteImport } from './routes/admin/packages/route'
import { Route as AdminFlashcardsRouteRouteImport } from './routes/admin/flashcards/route'
import { Route as AdminDashboardRouteRouteImport } from './routes/admin/dashboard/route'
import { Route as AdminCoursesRouteRouteImport } from './routes/admin/courses/route'
import { Route as AdminBooksRouteRouteImport } from './routes/admin/books/route'
import { Route as AdminAssignmentRouteRouteImport } from './routes/admin/assignment/route'
import { Route as AdminArchiveRouteRouteImport } from './routes/admin/archive/route'
import { Route as appWalletRouteRouteImport } from './routes/(app)/wallet/route'
import { Route as appSubscriptionRouteRouteImport } from './routes/(app)/subscription/route'
import { Route as appRefundRouteRouteImport } from './routes/(app)/refund/route'
import { Route as appProfileRouteRouteImport } from './routes/(app)/profile/route'
import { Route as appChatTrizRouteRouteImport } from './routes/(app)/chat-triz/route'
import { Route as BooksBookIdIndexRouteImport } from './routes/books.$bookId.index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as appQuizIndexRouteImport } from './routes/(app)/quiz/index'
import { Route as appGamesIndexRouteImport } from './routes/(app)/games/index'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin/users/$userId'
import { Route as appGamesSegmentationGameRouteImport } from './routes/(app)/games/segmentation-game'
import { Route as appGamesPreliminaryGameRouteImport } from './routes/(app)/games/preliminary-game'
import { Route as appGamesMergingGameRouteImport } from './routes/(app)/games/merging-game'
import { Route as appGamesMemoryCardRouteImport } from './routes/(app)/games/memory-card'
import { Route as AdminCoursesCreateRouteRouteImport } from './routes/admin/courses/create/route'
import { Route as appQuizHistoryRouteRouteImport } from './routes/(app)/quiz/history/route'
import { Route as appQuizQuizIdRouteRouteImport } from './routes/(app)/quiz/$quizId/route'
import { Route as appCourseMyCourseRouteRouteImport } from './routes/(app)/course/my-course/route'
import { Route as appBooksMeRouteRouteImport } from './routes/(app)/books/me/route'
import { Route as AdminCoursesIndexRouteRouteImport } from './routes/admin/courses/index/route'
import { Route as appCourseQuizSlugRouteRouteImport } from './routes/(app)/course/quiz/$slug/route'
import { Route as appCourseLearnSlugRouteRouteImport } from './routes/(app)/course/learn/$slug/route'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const MatrixTrizRoute = MatrixTrizRouteImport.update({
  id: '/matrix-triz',
  path: '/matrix-triz',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnTrizRoute = LearnTrizRouteImport.update({
  id: '/learn-triz',
  path: '/learn-triz',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardDeckRoute = FlashcardDeckRouteImport.update({
  id: '/flashcard-deck',
  path: '/flashcard-deck',
  getParentRoute: () => rootRouteImport,
} as any)
const R6StepsRouteRoute = R6StepsRouteRouteImport.update({
  id: '/6-steps',
  path: '/6-steps',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesIndexRoute = PackagesIndexRouteImport.update({
  id: '/packages/',
  path: '/packages/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordIndexRoute = ForgotPasswordIndexRouteImport.update({
  id: '/forgot-password/',
  path: '/forgot-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseIndexRoute = CourseIndexRouteImport.update({
  id: '/course/',
  path: '/course/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksIndexRoute = BooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterVerifyOtpRoute = RegisterVerifyOtpRouteImport.update({
  id: '/register/verify-otp',
  path: '/register/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordVerifyOtpRoute = ForgotPasswordVerifyOtpRouteImport.update({
  id: '/forgot-password/verify-otp',
  path: '/forgot-password/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordNewPasswordRoute =
  ForgotPasswordNewPasswordRouteImport.update({
    id: '/forgot-password/new-password',
    path: '/forgot-password/new-password',
    getParentRoute: () => rootRouteImport,
  } as any)
const FlashcardDeckIdRoute = FlashcardDeckIdRouteImport.update({
  id: '/flashcard/$deckId',
  path: '/flashcard/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseSlugRoute = CourseSlugRouteImport.update({
  id: '/course/$slug',
  path: '/course/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTransactionsRouteRoute = AdminTransactionsRouteRouteImport.update({
  id: '/admin/transactions',
  path: '/admin/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubscriptionsRouteRoute = AdminSubscriptionsRouteRouteImport.update({
  id: '/admin/subscriptions',
  path: '/admin/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQuizzesRouteRoute = AdminQuizzesRouteRouteImport.update({
  id: '/admin/quizzes',
  path: '/admin/quizzes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPackagesRouteRoute = AdminPackagesRouteRouteImport.update({
  id: '/admin/packages',
  path: '/admin/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFlashcardsRouteRoute = AdminFlashcardsRouteRouteImport.update({
  id: '/admin/flashcards',
  path: '/admin/flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRouteRoute = AdminDashboardRouteRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoursesRouteRoute = AdminCoursesRouteRouteImport.update({
  id: '/admin/courses',
  path: '/admin/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBooksRouteRoute = AdminBooksRouteRouteImport.update({
  id: '/admin/books',
  path: '/admin/books',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAssignmentRouteRoute = AdminAssignmentRouteRouteImport.update({
  id: '/admin/assignment',
  path: '/admin/assignment',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminArchiveRouteRoute = AdminArchiveRouteRouteImport.update({
  id: '/admin/archive',
  path: '/admin/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const appWalletRouteRoute = appWalletRouteRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => appRouteRoute,
} as any)
const appSubscriptionRouteRoute = appSubscriptionRouteRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => appRouteRoute,
} as any)
const appRefundRouteRoute = appRefundRouteRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => appRouteRoute,
} as any)
const appProfileRouteRoute = appProfileRouteRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => appRouteRoute,
} as any)
const appChatTrizRouteRoute = appChatTrizRouteRouteImport.update({
  id: '/chat-triz',
  path: '/chat-triz',
  getParentRoute: () => appRouteRoute,
} as any)
const BooksBookIdIndexRoute = BooksBookIdIndexRouteImport.update({
  id: '/books/$bookId/',
  path: '/books/$bookId/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const appQuizIndexRoute = appQuizIndexRouteImport.update({
  id: '/quiz/',
  path: '/quiz/',
  getParentRoute: () => appRouteRoute,
} as any)
const appGamesIndexRoute = appGamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => appRouteRoute,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/admin/users/$userId',
  path: '/admin/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const appGamesSegmentationGameRoute =
  appGamesSegmentationGameRouteImport.update({
    id: '/games/segmentation-game',
    path: '/games/segmentation-game',
    getParentRoute: () => appRouteRoute,
  } as any)
const appGamesPreliminaryGameRoute = appGamesPreliminaryGameRouteImport.update({
  id: '/games/preliminary-game',
  path: '/games/preliminary-game',
  getParentRoute: () => appRouteRoute,
} as any)
const appGamesMergingGameRoute = appGamesMergingGameRouteImport.update({
  id: '/games/merging-game',
  path: '/games/merging-game',
  getParentRoute: () => appRouteRoute,
} as any)
const appGamesMemoryCardRoute = appGamesMemoryCardRouteImport.update({
  id: '/games/memory-card',
  path: '/games/memory-card',
  getParentRoute: () => appRouteRoute,
} as any)
const AdminCoursesCreateRouteRoute = AdminCoursesCreateRouteRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AdminCoursesRouteRoute,
} as any)
const appQuizHistoryRouteRoute = appQuizHistoryRouteRouteImport.update({
  id: '/quiz/history',
  path: '/quiz/history',
  getParentRoute: () => appRouteRoute,
} as any)
const appQuizQuizIdRouteRoute = appQuizQuizIdRouteRouteImport.update({
  id: '/quiz/$quizId',
  path: '/quiz/$quizId',
  getParentRoute: () => appRouteRoute,
} as any)
const appCourseMyCourseRouteRoute = appCourseMyCourseRouteRouteImport.update({
  id: '/course/my-course',
  path: '/course/my-course',
  getParentRoute: () => appRouteRoute,
} as any)
const appBooksMeRouteRoute = appBooksMeRouteRouteImport.update({
  id: '/books/me',
  path: '/books/me',
  getParentRoute: () => appRouteRoute,
} as any)
const AdminCoursesIndexRouteRoute = AdminCoursesIndexRouteRouteImport.update({
  id: '/',
  path: '',
  getParentRoute: () => AdminCoursesRouteRoute,
} as any)
const appCourseQuizSlugRouteRoute = appCourseQuizSlugRouteRouteImport.update({
  id: '/course/quiz/$slug',
  path: '/course/quiz/$slug',
  getParentRoute: () => appRouteRoute,
} as any)
const appCourseLearnSlugRouteRoute = appCourseLearnSlugRouteRouteImport.update({
  id: '/course/learn/$slug',
  path: '/course/learn/$slug',
  getParentRoute: () => appRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/6-steps': typeof R6StepsRouteRoute
  '/flashcard-deck': typeof FlashcardDeckRoute
  '/home': typeof HomeRoute
  '/learn-triz': typeof LearnTrizRoute
  '/login': typeof LoginRoute
  '/matrix-triz': typeof MatrixTrizRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/chat-triz': typeof appChatTrizRouteRoute
  '/profile': typeof appProfileRouteRoute
  '/refund': typeof appRefundRouteRoute
  '/subscription': typeof appSubscriptionRouteRoute
  '/wallet': typeof appWalletRouteRoute
  '/admin/archive': typeof AdminArchiveRouteRoute
  '/admin/assignment': typeof AdminAssignmentRouteRoute
  '/admin/books': typeof AdminBooksRouteRoute
  '/admin/courses': typeof AdminCoursesIndexRouteRoute
  '/admin/dashboard': typeof AdminDashboardRouteRoute
  '/admin/flashcards': typeof AdminFlashcardsRouteRoute
  '/admin/packages': typeof AdminPackagesRouteRoute
  '/admin/quizzes': typeof AdminQuizzesRouteRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRouteRoute
  '/admin/transactions': typeof AdminTransactionsRouteRoute
  '/course/$slug': typeof CourseSlugRoute
  '/flashcard/$deckId': typeof FlashcardDeckIdRoute
  '/forgot-password/new-password': typeof ForgotPasswordNewPasswordRoute
  '/forgot-password/verify-otp': typeof ForgotPasswordVerifyOtpRoute
  '/register/verify-otp': typeof RegisterVerifyOtpRoute
  '/admin': typeof AdminIndexRoute
  '/books': typeof BooksIndexRoute
  '/course': typeof CourseIndexRoute
  '/forgot-password': typeof ForgotPasswordIndexRoute
  '/packages': typeof PackagesIndexRoute
  '/register': typeof RegisterIndexRoute
  '/books/me': typeof appBooksMeRouteRoute
  '/course/my-course': typeof appCourseMyCourseRouteRoute
  '/quiz/$quizId': typeof appQuizQuizIdRouteRoute
  '/quiz/history': typeof appQuizHistoryRouteRoute
  '/admin/courses/create': typeof AdminCoursesCreateRouteRoute
  '/games/memory-card': typeof appGamesMemoryCardRoute
  '/games/merging-game': typeof appGamesMergingGameRoute
  '/games/preliminary-game': typeof appGamesPreliminaryGameRoute
  '/games/segmentation-game': typeof appGamesSegmentationGameRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/games': typeof appGamesIndexRoute
  '/quiz': typeof appQuizIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/books/$bookId': typeof BooksBookIdIndexRoute
  '/course/learn/$slug': typeof appCourseLearnSlugRouteRoute
  '/course/quiz/$slug': typeof appCourseQuizSlugRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/6-steps': typeof R6StepsRouteRoute
  '/flashcard-deck': typeof FlashcardDeckRoute
  '/home': typeof HomeRoute
  '/learn-triz': typeof LearnTrizRoute
  '/login': typeof LoginRoute
  '/matrix-triz': typeof MatrixTrizRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/chat-triz': typeof appChatTrizRouteRoute
  '/profile': typeof appProfileRouteRoute
  '/refund': typeof appRefundRouteRoute
  '/subscription': typeof appSubscriptionRouteRoute
  '/wallet': typeof appWalletRouteRoute
  '/admin/archive': typeof AdminArchiveRouteRoute
  '/admin/assignment': typeof AdminAssignmentRouteRoute
  '/admin/books': typeof AdminBooksRouteRoute
  '/admin/courses': typeof AdminCoursesIndexRouteRoute
  '/admin/dashboard': typeof AdminDashboardRouteRoute
  '/admin/flashcards': typeof AdminFlashcardsRouteRoute
  '/admin/packages': typeof AdminPackagesRouteRoute
  '/admin/quizzes': typeof AdminQuizzesRouteRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRouteRoute
  '/admin/transactions': typeof AdminTransactionsRouteRoute
  '/course/$slug': typeof CourseSlugRoute
  '/flashcard/$deckId': typeof FlashcardDeckIdRoute
  '/forgot-password/new-password': typeof ForgotPasswordNewPasswordRoute
  '/forgot-password/verify-otp': typeof ForgotPasswordVerifyOtpRoute
  '/register/verify-otp': typeof RegisterVerifyOtpRoute
  '/admin': typeof AdminIndexRoute
  '/books': typeof BooksIndexRoute
  '/course': typeof CourseIndexRoute
  '/forgot-password': typeof ForgotPasswordIndexRoute
  '/packages': typeof PackagesIndexRoute
  '/register': typeof RegisterIndexRoute
  '/books/me': typeof appBooksMeRouteRoute
  '/course/my-course': typeof appCourseMyCourseRouteRoute
  '/quiz/$quizId': typeof appQuizQuizIdRouteRoute
  '/quiz/history': typeof appQuizHistoryRouteRoute
  '/admin/courses/create': typeof AdminCoursesCreateRouteRoute
  '/games/memory-card': typeof appGamesMemoryCardRoute
  '/games/merging-game': typeof appGamesMergingGameRoute
  '/games/preliminary-game': typeof appGamesPreliminaryGameRoute
  '/games/segmentation-game': typeof appGamesSegmentationGameRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/games': typeof appGamesIndexRoute
  '/quiz': typeof appQuizIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/books/$bookId': typeof BooksBookIdIndexRoute
  '/course/learn/$slug': typeof appCourseLearnSlugRouteRoute
  '/course/quiz/$slug': typeof appCourseQuizSlugRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)': typeof appRouteRouteWithChildren
  '/6-steps': typeof R6StepsRouteRoute
  '/flashcard-deck': typeof FlashcardDeckRoute
  '/home': typeof HomeRoute
  '/learn-triz': typeof LearnTrizRoute
  '/login': typeof LoginRoute
  '/matrix-triz': typeof MatrixTrizRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/(app)/chat-triz': typeof appChatTrizRouteRoute
  '/(app)/profile': typeof appProfileRouteRoute
  '/(app)/refund': typeof appRefundRouteRoute
  '/(app)/subscription': typeof appSubscriptionRouteRoute
  '/(app)/wallet': typeof appWalletRouteRoute
  '/admin/archive': typeof AdminArchiveRouteRoute
  '/admin/assignment': typeof AdminAssignmentRouteRoute
  '/admin/books': typeof AdminBooksRouteRoute
  '/admin/courses': typeof AdminCoursesRouteRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRouteRoute
  '/admin/flashcards': typeof AdminFlashcardsRouteRoute
  '/admin/packages': typeof AdminPackagesRouteRoute
  '/admin/quizzes': typeof AdminQuizzesRouteRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRouteRoute
  '/admin/transactions': typeof AdminTransactionsRouteRoute
  '/course/$slug': typeof CourseSlugRoute
  '/flashcard/$deckId': typeof FlashcardDeckIdRoute
  '/forgot-password/new-password': typeof ForgotPasswordNewPasswordRoute
  '/forgot-password/verify-otp': typeof ForgotPasswordVerifyOtpRoute
  '/register/verify-otp': typeof RegisterVerifyOtpRoute
  '/admin/': typeof AdminIndexRoute
  '/books/': typeof BooksIndexRoute
  '/course/': typeof CourseIndexRoute
  '/forgot-password/': typeof ForgotPasswordIndexRoute
  '/packages/': typeof PackagesIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/admin/courses/': typeof AdminCoursesIndexRouteRoute
  '/(app)/books/me': typeof appBooksMeRouteRoute
  '/(app)/course/my-course': typeof appCourseMyCourseRouteRoute
  '/(app)/quiz/$quizId': typeof appQuizQuizIdRouteRoute
  '/(app)/quiz/history': typeof appQuizHistoryRouteRoute
  '/admin/courses/create': typeof AdminCoursesCreateRouteRoute
  '/(app)/games/memory-card': typeof appGamesMemoryCardRoute
  '/(app)/games/merging-game': typeof appGamesMergingGameRoute
  '/(app)/games/preliminary-game': typeof appGamesPreliminaryGameRoute
  '/(app)/games/segmentation-game': typeof appGamesSegmentationGameRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/(app)/games/': typeof appGamesIndexRoute
  '/(app)/quiz/': typeof appQuizIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/books/$bookId/': typeof BooksBookIdIndexRoute
  '/(app)/course/learn/$slug': typeof appCourseLearnSlugRouteRoute
  '/(app)/course/quiz/$slug': typeof appCourseQuizSlugRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/6-steps'
    | '/flashcard-deck'
    | '/home'
    | '/learn-triz'
    | '/login'
    | '/matrix-triz'
    | '/unauthorized'
    | '/chat-triz'
    | '/profile'
    | '/refund'
    | '/subscription'
    | '/wallet'
    | '/admin/archive'
    | '/admin/assignment'
    | '/admin/books'
    | '/admin/courses'
    | '/admin/dashboard'
    | '/admin/flashcards'
    | '/admin/packages'
    | '/admin/quizzes'
    | '/admin/subscriptions'
    | '/admin/transactions'
    | '/course/$slug'
    | '/flashcard/$deckId'
    | '/forgot-password/new-password'
    | '/forgot-password/verify-otp'
    | '/register/verify-otp'
    | '/admin'
    | '/books'
    | '/course'
    | '/forgot-password'
    | '/packages'
    | '/register'
    | '/books/me'
    | '/course/my-course'
    | '/quiz/$quizId'
    | '/quiz/history'
    | '/admin/courses/create'
    | '/games/memory-card'
    | '/games/merging-game'
    | '/games/preliminary-game'
    | '/games/segmentation-game'
    | '/admin/users/$userId'
    | '/games'
    | '/quiz'
    | '/admin/users'
    | '/books/$bookId'
    | '/course/learn/$slug'
    | '/course/quiz/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/6-steps'
    | '/flashcard-deck'
    | '/home'
    | '/learn-triz'
    | '/login'
    | '/matrix-triz'
    | '/unauthorized'
    | '/chat-triz'
    | '/profile'
    | '/refund'
    | '/subscription'
    | '/wallet'
    | '/admin/archive'
    | '/admin/assignment'
    | '/admin/books'
    | '/admin/courses'
    | '/admin/dashboard'
    | '/admin/flashcards'
    | '/admin/packages'
    | '/admin/quizzes'
    | '/admin/subscriptions'
    | '/admin/transactions'
    | '/course/$slug'
    | '/flashcard/$deckId'
    | '/forgot-password/new-password'
    | '/forgot-password/verify-otp'
    | '/register/verify-otp'
    | '/admin'
    | '/books'
    | '/course'
    | '/forgot-password'
    | '/packages'
    | '/register'
    | '/books/me'
    | '/course/my-course'
    | '/quiz/$quizId'
    | '/quiz/history'
    | '/admin/courses/create'
    | '/games/memory-card'
    | '/games/merging-game'
    | '/games/preliminary-game'
    | '/games/segmentation-game'
    | '/admin/users/$userId'
    | '/games'
    | '/quiz'
    | '/admin/users'
    | '/books/$bookId'
    | '/course/learn/$slug'
    | '/course/quiz/$slug'
  id:
    | '__root__'
    | '/'
    | '/(app)'
    | '/6-steps'
    | '/flashcard-deck'
    | '/home'
    | '/learn-triz'
    | '/login'
    | '/matrix-triz'
    | '/unauthorized'
    | '/(app)/chat-triz'
    | '/(app)/profile'
    | '/(app)/refund'
    | '/(app)/subscription'
    | '/(app)/wallet'
    | '/admin/archive'
    | '/admin/assignment'
    | '/admin/books'
    | '/admin/courses'
    | '/admin/dashboard'
    | '/admin/flashcards'
    | '/admin/packages'
    | '/admin/quizzes'
    | '/admin/subscriptions'
    | '/admin/transactions'
    | '/course/$slug'
    | '/flashcard/$deckId'
    | '/forgot-password/new-password'
    | '/forgot-password/verify-otp'
    | '/register/verify-otp'
    | '/admin/'
    | '/books/'
    | '/course/'
    | '/forgot-password/'
    | '/packages/'
    | '/register/'
    | '/admin/courses/'
    | '/(app)/books/me'
    | '/(app)/course/my-course'
    | '/(app)/quiz/$quizId'
    | '/(app)/quiz/history'
    | '/admin/courses/create'
    | '/(app)/games/memory-card'
    | '/(app)/games/merging-game'
    | '/(app)/games/preliminary-game'
    | '/(app)/games/segmentation-game'
    | '/admin/users/$userId'
    | '/(app)/games/'
    | '/(app)/quiz/'
    | '/admin/users/'
    | '/books/$bookId/'
    | '/(app)/course/learn/$slug'
    | '/(app)/course/quiz/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appRouteRoute: typeof appRouteRouteWithChildren
  R6StepsRouteRoute: typeof R6StepsRouteRoute
  FlashcardDeckRoute: typeof FlashcardDeckRoute
  HomeRoute: typeof HomeRoute
  LearnTrizRoute: typeof LearnTrizRoute
  LoginRoute: typeof LoginRoute
  MatrixTrizRoute: typeof MatrixTrizRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  AdminArchiveRouteRoute: typeof AdminArchiveRouteRoute
  AdminAssignmentRouteRoute: typeof AdminAssignmentRouteRoute
  AdminBooksRouteRoute: typeof AdminBooksRouteRoute
  AdminCoursesRouteRoute: typeof AdminCoursesRouteRouteWithChildren
  AdminDashboardRouteRoute: typeof AdminDashboardRouteRoute
  AdminFlashcardsRouteRoute: typeof AdminFlashcardsRouteRoute
  AdminPackagesRouteRoute: typeof AdminPackagesRouteRoute
  AdminQuizzesRouteRoute: typeof AdminQuizzesRouteRoute
  AdminSubscriptionsRouteRoute: typeof AdminSubscriptionsRouteRoute
  AdminTransactionsRouteRoute: typeof AdminTransactionsRouteRoute
  CourseSlugRoute: typeof CourseSlugRoute
  FlashcardDeckIdRoute: typeof FlashcardDeckIdRoute
  ForgotPasswordNewPasswordRoute: typeof ForgotPasswordNewPasswordRoute
  ForgotPasswordVerifyOtpRoute: typeof ForgotPasswordVerifyOtpRoute
  RegisterVerifyOtpRoute: typeof RegisterVerifyOtpRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BooksIndexRoute: typeof BooksIndexRoute
  CourseIndexRoute: typeof CourseIndexRoute
  ForgotPasswordIndexRoute: typeof ForgotPasswordIndexRoute
  PackagesIndexRoute: typeof PackagesIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  BooksBookIdIndexRoute: typeof BooksBookIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matrix-triz': {
      id: '/matrix-triz'
      path: '/matrix-triz'
      fullPath: '/matrix-triz'
      preLoaderRoute: typeof MatrixTrizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn-triz': {
      id: '/learn-triz'
      path: '/learn-triz'
      fullPath: '/learn-triz'
      preLoaderRoute: typeof LearnTrizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcard-deck': {
      id: '/flashcard-deck'
      path: '/flashcard-deck'
      fullPath: '/flashcard-deck'
      preLoaderRoute: typeof FlashcardDeckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/6-steps': {
      id: '/6-steps'
      path: '/6-steps'
      fullPath: '/6-steps'
      preLoaderRoute: typeof R6StepsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/': {
      id: '/packages/'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password/': {
      id: '/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/': {
      id: '/course/'
      path: '/course'
      fullPath: '/course'
      preLoaderRoute: typeof CourseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/': {
      id: '/books/'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/verify-otp': {
      id: '/register/verify-otp'
      path: '/register/verify-otp'
      fullPath: '/register/verify-otp'
      preLoaderRoute: typeof RegisterVerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password/verify-otp': {
      id: '/forgot-password/verify-otp'
      path: '/forgot-password/verify-otp'
      fullPath: '/forgot-password/verify-otp'
      preLoaderRoute: typeof ForgotPasswordVerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password/new-password': {
      id: '/forgot-password/new-password'
      path: '/forgot-password/new-password'
      fullPath: '/forgot-password/new-password'
      preLoaderRoute: typeof ForgotPasswordNewPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcard/$deckId': {
      id: '/flashcard/$deckId'
      path: '/flashcard/$deckId'
      fullPath: '/flashcard/$deckId'
      preLoaderRoute: typeof FlashcardDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$slug': {
      id: '/course/$slug'
      path: '/course/$slug'
      fullPath: '/course/$slug'
      preLoaderRoute: typeof CourseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/admin/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/admin/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/quizzes': {
      id: '/admin/quizzes'
      path: '/admin/quizzes'
      fullPath: '/admin/quizzes'
      preLoaderRoute: typeof AdminQuizzesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/packages': {
      id: '/admin/packages'
      path: '/admin/packages'
      fullPath: '/admin/packages'
      preLoaderRoute: typeof AdminPackagesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/flashcards': {
      id: '/admin/flashcards'
      path: '/admin/flashcards'
      fullPath: '/admin/flashcards'
      preLoaderRoute: typeof AdminFlashcardsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/admin/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/books': {
      id: '/admin/books'
      path: '/admin/books'
      fullPath: '/admin/books'
      preLoaderRoute: typeof AdminBooksRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/assignment': {
      id: '/admin/assignment'
      path: '/admin/assignment'
      fullPath: '/admin/assignment'
      preLoaderRoute: typeof AdminAssignmentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/archive': {
      id: '/admin/archive'
      path: '/admin/archive'
      fullPath: '/admin/archive'
      preLoaderRoute: typeof AdminArchiveRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/wallet': {
      id: '/(app)/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof appWalletRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/subscription': {
      id: '/(app)/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof appSubscriptionRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/refund': {
      id: '/(app)/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof appRefundRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/profile': {
      id: '/(app)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof appProfileRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/chat-triz': {
      id: '/(app)/chat-triz'
      path: '/chat-triz'
      fullPath: '/chat-triz'
      preLoaderRoute: typeof appChatTrizRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/books/$bookId/': {
      id: '/books/$bookId/'
      path: '/books/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof BooksBookIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/quiz/': {
      id: '/(app)/quiz/'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof appQuizIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/games/': {
      id: '/(app)/games/'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof appGamesIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/admin/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/games/segmentation-game': {
      id: '/(app)/games/segmentation-game'
      path: '/games/segmentation-game'
      fullPath: '/games/segmentation-game'
      preLoaderRoute: typeof appGamesSegmentationGameRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/games/preliminary-game': {
      id: '/(app)/games/preliminary-game'
      path: '/games/preliminary-game'
      fullPath: '/games/preliminary-game'
      preLoaderRoute: typeof appGamesPreliminaryGameRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/games/merging-game': {
      id: '/(app)/games/merging-game'
      path: '/games/merging-game'
      fullPath: '/games/merging-game'
      preLoaderRoute: typeof appGamesMergingGameRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/games/memory-card': {
      id: '/(app)/games/memory-card'
      path: '/games/memory-card'
      fullPath: '/games/memory-card'
      preLoaderRoute: typeof appGamesMemoryCardRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/admin/courses/create': {
      id: '/admin/courses/create'
      path: '/create'
      fullPath: '/admin/courses/create'
      preLoaderRoute: typeof AdminCoursesCreateRouteRouteImport
      parentRoute: typeof AdminCoursesRouteRoute
    }
    '/(app)/quiz/history': {
      id: '/(app)/quiz/history'
      path: '/quiz/history'
      fullPath: '/quiz/history'
      preLoaderRoute: typeof appQuizHistoryRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/quiz/$quizId': {
      id: '/(app)/quiz/$quizId'
      path: '/quiz/$quizId'
      fullPath: '/quiz/$quizId'
      preLoaderRoute: typeof appQuizQuizIdRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/course/my-course': {
      id: '/(app)/course/my-course'
      path: '/course/my-course'
      fullPath: '/course/my-course'
      preLoaderRoute: typeof appCourseMyCourseRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/books/me': {
      id: '/(app)/books/me'
      path: '/books/me'
      fullPath: '/books/me'
      preLoaderRoute: typeof appBooksMeRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/admin/courses/': {
      id: '/admin/courses/'
      path: ''
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesIndexRouteRouteImport
      parentRoute: typeof AdminCoursesRouteRoute
    }
    '/(app)/course/quiz/$slug': {
      id: '/(app)/course/quiz/$slug'
      path: '/course/quiz/$slug'
      fullPath: '/course/quiz/$slug'
      preLoaderRoute: typeof appCourseQuizSlugRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/course/learn/$slug': {
      id: '/(app)/course/learn/$slug'
      path: '/course/learn/$slug'
      fullPath: '/course/learn/$slug'
      preLoaderRoute: typeof appCourseLearnSlugRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
  }
}

interface appRouteRouteChildren {
  appChatTrizRouteRoute: typeof appChatTrizRouteRoute
  appProfileRouteRoute: typeof appProfileRouteRoute
  appRefundRouteRoute: typeof appRefundRouteRoute
  appSubscriptionRouteRoute: typeof appSubscriptionRouteRoute
  appWalletRouteRoute: typeof appWalletRouteRoute
  appBooksMeRouteRoute: typeof appBooksMeRouteRoute
  appCourseMyCourseRouteRoute: typeof appCourseMyCourseRouteRoute
  appQuizQuizIdRouteRoute: typeof appQuizQuizIdRouteRoute
  appQuizHistoryRouteRoute: typeof appQuizHistoryRouteRoute
  appGamesMemoryCardRoute: typeof appGamesMemoryCardRoute
  appGamesMergingGameRoute: typeof appGamesMergingGameRoute
  appGamesPreliminaryGameRoute: typeof appGamesPreliminaryGameRoute
  appGamesSegmentationGameRoute: typeof appGamesSegmentationGameRoute
  appGamesIndexRoute: typeof appGamesIndexRoute
  appQuizIndexRoute: typeof appQuizIndexRoute
  appCourseLearnSlugRouteRoute: typeof appCourseLearnSlugRouteRoute
  appCourseQuizSlugRouteRoute: typeof appCourseQuizSlugRouteRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appChatTrizRouteRoute: appChatTrizRouteRoute,
  appProfileRouteRoute: appProfileRouteRoute,
  appRefundRouteRoute: appRefundRouteRoute,
  appSubscriptionRouteRoute: appSubscriptionRouteRoute,
  appWalletRouteRoute: appWalletRouteRoute,
  appBooksMeRouteRoute: appBooksMeRouteRoute,
  appCourseMyCourseRouteRoute: appCourseMyCourseRouteRoute,
  appQuizQuizIdRouteRoute: appQuizQuizIdRouteRoute,
  appQuizHistoryRouteRoute: appQuizHistoryRouteRoute,
  appGamesMemoryCardRoute: appGamesMemoryCardRoute,
  appGamesMergingGameRoute: appGamesMergingGameRoute,
  appGamesPreliminaryGameRoute: appGamesPreliminaryGameRoute,
  appGamesSegmentationGameRoute: appGamesSegmentationGameRoute,
  appGamesIndexRoute: appGamesIndexRoute,
  appQuizIndexRoute: appQuizIndexRoute,
  appCourseLearnSlugRouteRoute: appCourseLearnSlugRouteRoute,
  appCourseQuizSlugRouteRoute: appCourseQuizSlugRouteRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

interface AdminCoursesRouteRouteChildren {
  AdminCoursesIndexRouteRoute: typeof AdminCoursesIndexRouteRoute
  AdminCoursesCreateRouteRoute: typeof AdminCoursesCreateRouteRoute
}

const AdminCoursesRouteRouteChildren: AdminCoursesRouteRouteChildren = {
  AdminCoursesIndexRouteRoute: AdminCoursesIndexRouteRoute,
  AdminCoursesCreateRouteRoute: AdminCoursesCreateRouteRoute,
}

const AdminCoursesRouteRouteWithChildren =
  AdminCoursesRouteRoute._addFileChildren(AdminCoursesRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appRouteRoute: appRouteRouteWithChildren,
  R6StepsRouteRoute: R6StepsRouteRoute,
  FlashcardDeckRoute: FlashcardDeckRoute,
  HomeRoute: HomeRoute,
  LearnTrizRoute: LearnTrizRoute,
  LoginRoute: LoginRoute,
  MatrixTrizRoute: MatrixTrizRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  AdminArchiveRouteRoute: AdminArchiveRouteRoute,
  AdminAssignmentRouteRoute: AdminAssignmentRouteRoute,
  AdminBooksRouteRoute: AdminBooksRouteRoute,
  AdminCoursesRouteRoute: AdminCoursesRouteRouteWithChildren,
  AdminDashboardRouteRoute: AdminDashboardRouteRoute,
  AdminFlashcardsRouteRoute: AdminFlashcardsRouteRoute,
  AdminPackagesRouteRoute: AdminPackagesRouteRoute,
  AdminQuizzesRouteRoute: AdminQuizzesRouteRoute,
  AdminSubscriptionsRouteRoute: AdminSubscriptionsRouteRoute,
  AdminTransactionsRouteRoute: AdminTransactionsRouteRoute,
  CourseSlugRoute: CourseSlugRoute,
  FlashcardDeckIdRoute: FlashcardDeckIdRoute,
  ForgotPasswordNewPasswordRoute: ForgotPasswordNewPasswordRoute,
  ForgotPasswordVerifyOtpRoute: ForgotPasswordVerifyOtpRoute,
  RegisterVerifyOtpRoute: RegisterVerifyOtpRoute,
  AdminIndexRoute: AdminIndexRoute,
  BooksIndexRoute: BooksIndexRoute,
  CourseIndexRoute: CourseIndexRoute,
  ForgotPasswordIndexRoute: ForgotPasswordIndexRoute,
  PackagesIndexRoute: PackagesIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  BooksBookIdIndexRoute: BooksBookIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
